import { Inter } from "next/font/google";
import "./globals.css";
import { ApolloWrapper } from "./ApolloWrapper";
import Header from '../components/LandingPage/Header'
import Footer from '../components/LandingPage/Footer'
import { Roboto } from "next/font/google";
const inter = Inter({ subsets: ["latin"] });

const roboto =({
  weight:['500'],
  style:['normal'],
  subsets:['latin'],
  display:'swap'
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <div className="relative w-3/4 mx-auto ">
          <Header/>
        
      <ApolloWrapper>{children}</ApolloWrapper>
      <Footer/>
      </div>
      </body>
    </html>
  );
}
